# Generated by Django 5.1 on 2024-09-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_userdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='mobile_number',
            new_name='mobile',
        ),
    ]
